name: Build All

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout HEAD only
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Check for changes since nightly
        id: check
        run: |
          git fetch origin refs/tags/nightly:refs/tags/nightly || true
          if git rev-parse nightly >/dev/null 2>&1; then
            nightly_commit=$(git rev-list -n 1 nightly)
            head_commit=$(git rev-parse HEAD)
            echo "Nightly tag commit: $nightly_commit"
            echo "HEAD commit: $head_commit"

            if [ "$nightly_commit" = "$head_commit" ]; then
              echo "No new commits since nightly release"
              echo "should_build=false" >> $GITHUB_OUTPUT
            else
              echo "New commits found since nightly release"
              echo "should_build=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "No 'nightly' tag found - will build"
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi

  skip-build:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: needs.check-for-changes.outputs.should_build != 'true'
    steps:
    - run: echo "Nothing changed"
    
  build-linux32:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: needs.check-for-changes.outputs.should_build == 'true'
    permissions:
      contents: write

    steps:
    - name: Detect CI platform
      run: |
        if [[ "$GITHUB_SERVER_URL" == *"github"* ]]; then
          echo "CI_PLATFORM=github" >> $GITHUB_ENV
          echo "Detected platform: github"
        else
          echo "CI_PLATFORM=gitea" >> $GITHUB_ENV
          echo "Detected platform: gitea"
        fi

    - name: Install necessary utils
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-i686-linux-gnu
        sudo ln -s /usr/bin/i686-linux-gnu-ld /usr/local/bin/i386-linux-ld
      
    - name: Install bootstrap compiler (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      run: sudo apt-get install -y fpc-3.2.2
      
    - name: Install bootstrap compiler (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      run: |
        wget --tries=3 --timeout=10 https://downloads.freepascal.org/fpc/dist/3.2.2/x86_64-linux/fpc-3.2.2.x86_64-linux.tar
        echo "5ADAC308A5534B6A76446D8311FC340747CBB7EDEAACFE6B651493FF3FE31E83 fpc-3.2.2.x86_64-linux.tar" | sha256sum -c -
        tar -xf fpc-3.2.2.x86_64-linux.tar
        cd fpc-3.2.2.x86_64-linux
        echo "/usr/local" | ./install.sh
      
    - name: Check bootstrap compiler version
      run: fpc -iVTOTP
    
    - name: Checkout source
      uses: actions/checkout@v3
      
    - name: Build FPC
      run: |
        make distclean
        make all OS_TARGET=linux CPU_TARGET=i386
        make install OS_TARGET=linux CPU_TARGET=i386 INSTALL_PREFIX=$PWD/fpc

    - name: Package artifacts
      run: |
        mv compiler/ppc386 fpc/bin
        mv fpc/lib/fpc/3.3.1/units fpc/units
        rm -rf fpc/lib
        rm -rf fpc/share
        zip -rq fpc-unleashed-linux32.zip fpc

    - name: Upload artifacts (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      uses: actions/upload-artifact@v4
      with:
        name: linux32
        path: fpc-unleashed-linux32.zip

    - name: Upload artifacts (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      uses: 'christopherhx/gitea-upload-artifact@v4'
      with:
        name: linux32
        path: fpc-unleashed-linux32.zip

  build-linux64:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: needs.check-for-changes.outputs.should_build == 'true'
    permissions:
      contents: write
      
    steps:
    - name: Detect CI platform
      run: |
        if [[ "$GITHUB_SERVER_URL" == *"github"* ]]; then
          echo "CI_PLATFORM=github" >> $GITHUB_ENV
          echo "Detected platform: github"
        else
          echo "CI_PLATFORM=gitea" >> $GITHUB_ENV
          echo "Detected platform: gitea"
        fi
        
    - name: Install bootstrap compiler (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y fpc-3.2.2
      
    - name: Install bootstrap compiler (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      run: |
        wget --tries=3 --timeout=10 https://downloads.freepascal.org/fpc/dist/3.2.2/x86_64-linux/fpc-3.2.2.x86_64-linux.tar
        echo "5ADAC308A5534B6A76446D8311FC340747CBB7EDEAACFE6B651493FF3FE31E83 fpc-3.2.2.x86_64-linux.tar" | sha256sum -c -
        tar -xf fpc-3.2.2.x86_64-linux.tar
        cd fpc-3.2.2.x86_64-linux
        echo "/usr/local" | ./install.sh

    - name: Check bootstrap compiler version
      run: fpc -iVTOTP

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build FPC
      run: |
        make distclean
        make all OS_TARGET=linux CPU_TARGET=x86_64
        make install OS_TARGET=linux CPU_TARGET=x86_64 INSTALL_PREFIX=$PWD/fpc

    - name: Package artifacts
      run: |
        mv compiler/ppcx64 fpc/bin
        mv fpc/lib/fpc/3.3.1/units fpc/units
        rm -rf fpc/lib
        rm -rf fpc/share
        zip -rq fpc-unleashed-linux64.zip fpc

    - name: Upload artifacts (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      uses: actions/upload-artifact@v4
      with:
        name: linux64
        path: fpc-unleashed-linux64.zip

    - name: Upload artifacts (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      uses: 'christopherhx/gitea-upload-artifact@v4'
      with:
        name: linux64
        path: fpc-unleashed-linux64.zip

  build-win32:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: needs.check-for-changes.outputs.should_build == 'true'
    permissions:
      contents: write
      
    steps:
    - name: Detect CI platform
      run: |
        if [[ "$GITHUB_SERVER_URL" == *"github"* ]]; then
          echo "CI_PLATFORM=github" >> $GITHUB_ENV
          echo "Detected platform: github"
        else
          echo "CI_PLATFORM=gitea" >> $GITHUB_ENV
          echo "Detected platform: gitea"
        fi
        
    - name: Install bootstrap compiler (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y fpc-3.2.2
      
    - name: Install bootstrap compiler (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      run: |
        wget --tries=3 --timeout=10 https://downloads.freepascal.org/fpc/dist/3.2.2/x86_64-linux/fpc-3.2.2.x86_64-linux.tar
        echo "5ADAC308A5534B6A76446D8311FC340747CBB7EDEAACFE6B651493FF3FE31E83 fpc-3.2.2.x86_64-linux.tar" | sha256sum -c -
        tar -xf fpc-3.2.2.x86_64-linux.tar
        cd fpc-3.2.2.x86_64-linux
        echo "/usr/local" | ./install.sh
        
    - name: Check bootstrap compiler version
      run: fpc -iVTOTP

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build FPC
      run: |
        make distclean
        make all OS_TARGET=win32 CPU_TARGET=i386
        make install OS_TARGET=win32 CPU_TARGET=i386 INSTALL_PREFIX=$PWD/fpc

    - name: Package artifacts
      run: |
        mv compiler/ppc386.exe fpc/bin
        mv fpc/lib/fpc/3.3.1/units fpc/units
        rm -rf fpc/lib
        rm -rf fpc/share
        zip -rq fpc-unleashed-win32.zip fpc

    - name: Upload artifacts (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      uses: actions/upload-artifact@v4
      with:
        name: win32
        path: fpc-unleashed-win32.zip

    - name: Upload artifacts (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      uses: 'christopherhx/gitea-upload-artifact@v4'
      with:
        name: win32
        path: fpc-unleashed-win32.zip

  build-win64:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: needs.check-for-changes.outputs.should_build == 'true'
    permissions:
      contents: write
      
    steps:
    - name: Detect CI platform
      run: |
        if [[ "$GITHUB_SERVER_URL" == *"github"* ]]; then
          echo "CI_PLATFORM=github" >> $GITHUB_ENV
          echo "Detected platform: github"
        else
          echo "CI_PLATFORM=gitea" >> $GITHUB_ENV
          echo "Detected platform: gitea"
        fi
        
    - name: Install bootstrap compiler (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y fpc-3.2.2
      
    - name: Install bootstrap compiler (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      run: |
        wget --tries=3 --timeout=10 https://downloads.freepascal.org/fpc/dist/3.2.2/x86_64-linux/fpc-3.2.2.x86_64-linux.tar
        echo "5ADAC308A5534B6A76446D8311FC340747CBB7EDEAACFE6B651493FF3FE31E83 fpc-3.2.2.x86_64-linux.tar" | sha256sum -c -
        tar -xf fpc-3.2.2.x86_64-linux.tar
        cd fpc-3.2.2.x86_64-linux
        echo "/usr/local" | ./install.sh

    - name: Check bootstrap compiler version
      run: fpc -iVTOTP

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build FPC
      run: |
        make distclean
        make all OS_TARGET=win64 CPU_TARGET=x86_64
        make install OS_TARGET=win64 CPU_TARGET=x86_64 INSTALL_PREFIX=$PWD/fpc

    - name: Package artifacts
      run: |
        mv compiler/ppcx64.exe fpc/bin
        mv fpc/lib/fpc/3.3.1/units fpc/units
        rm -rf fpc/lib
        rm -rf fpc/share
        zip -rq fpc-unleashed-win64.zip fpc

    - name: Upload artifacts (Github)
      if: ${{ env.CI_PLATFORM == 'github' }}
      uses: actions/upload-artifact@v4
      with:
        name: win64
        path: fpc-unleashed-win64.zip

    - name: Upload artifacts (Gitea)
      if: ${{ env.CI_PLATFORM == 'gitea' }}
      uses: 'christopherhx/gitea-upload-artifact@v4'
      with:
        name: win64
        path: fpc-unleashed-win64.zip
          
  release-github:
    runs-on: ubuntu-latest
    needs: [build-linux32, build-linux64, build-win32, build-win64]
    if: ${{ contains(github.server_url, 'github') }}
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      
    - name: Download Linux32 artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux32
        path: .

    - name: Download Linux64 artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux64
        path: .
        
    - name: Download Win32 artifacts
      uses: actions/download-artifact@v4
      with:
        name: win32
        path: .

    - name: Download Win64 artifacts
      uses: actions/download-artifact@v4
      with:
        name: win64
        path: .
        
    - name: Update tag
      uses: richardsimko/update-tag@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        
    - name: Prepare release
      run: |
        ts=$(TZ=Europe/Berlin date +"%Y-%m-%d %H:%M:%S CEST")
        echo "TAG=nightly" >> $GITHUB_ENV
        echo "NAME=FPC Unleashed nightly" >> $GITHUB_ENV
        {
          echo "FPC Unleashed nightly build"
          echo
          echo "Generated from commit: $GITHUB_SHA"
          echo "Build time: $ts"
        } > release.txt
    
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: fpc-unleashed-linux32.zip,fpc-unleashed-linux64.zip,fpc-unleashed-win32.zip,fpc-unleashed-win64.zip
        tag: ${{ env.TAG }}
        name: ${{ env.NAME }}
        bodyFile: release.txt
        prerelease: true
        allowUpdates: true
  
  release-gitea:
    runs-on: ubuntu-latest
    needs: [build-linux32, build-linux64, build-win32, build-win64]
    if: ${{ !contains(github.server_url, 'github') }}
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Download Linux32 artifacts
      uses: 'christopherhx/gitea-download-artifact@v4'
      with:
        name: linux32
        path: .

    - name: Download Linux64 artifacts
      uses: 'christopherhx/gitea-download-artifact@v4'
      with:
        name: linux64
        path: .

    - name: Download Win32 artifacts
      uses: 'christopherhx/gitea-download-artifact@v4'
      with:
        name: win32
        path: .

    - name: Download Win64 artifacts
      uses: 'christopherhx/gitea-download-artifact@v4'
      with:
        name: win64
        path: .

    - name: Update tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag -d nightly || true
        git tag -f nightly HEAD
        git push origin -f refs/tags/nightly

    - name: Prepare release
      run: |
        ts=$(TZ=Europe/Berlin date +"%Y-%m-%d %H:%M:%S CEST")
        echo "TAG=nightly" >> $GITHUB_ENV
        echo "NAME=FPC Unleashed nightly" >> $GITHUB_ENV
        {
          echo "FPC Unleashed nightly build"
          echo
          echo "Generated from commit: $GITHUB_SHA"
          echo "Build time: $ts"
        } > release.txt

    - name: Release
      uses: akkuman/gitea-release-action@v1
      with:
        files: |
          fpc-unleashed-linux32.zip
          fpc-unleashed-linux64.zip
          fpc-unleashed-win32.zip
          fpc-unleashed-win64.zip
        tag_name: ${{ env.TAG }}
        target_commitish: $GITHUB_SHA
        name: ${{ env.NAME }}
        body_path: release.txt
        prerelease: true
        
