name: Check For Changes

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout HEAD only
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Check for changes since nightly
        id: check
        run: |
          git fetch origin refs/tags/nightly:refs/tags/nightly || true
          if git rev-parse nightly >/dev/null 2>&1; then
            nightly_commit=$(git rev-list -n 1 nightly)
            head_commit=$(git rev-parse HEAD)
            echo "Nightly tag commit: $nightly_commit"
            echo "HEAD commit: $head_commit"

            if [ "$nightly_commit" = "$head_commit" ]; then
              echo "No new commits since nightly release"
              echo "should_build=false" >> $GITHUB_OUTPUT
            else
              echo "New commits found since nightly release"
              echo "should_build=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "No 'nightly' tag found - will build"
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi
          
  changed:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: needs.check-for-changes.outputs.should_build == 'true'
    steps:
    - run: echo "Changed"

  skip:
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: needs.check-for-changes.outputs.should_build != 'true'
    steps:
    - run: echo "Not changed"
    
    
