# v2

name: CI

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'
    
jobs:
  windows:
    uses: ./.github/workflows/windows.yml
    permissions:
      contents: write
      
  linux:
    uses: ./.github/workflows/linux.yml
    permissions:
      contents: write
      
